# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-02 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativa', '0004_auto_20171101_0109'),
        ('productor', '0005_merge_20171022_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.IntegerField(blank=True, default=1, null=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=700)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 11, 16, 48, 476000), null=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Foro')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productor.Productor')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='foro',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Tema'),
        ),
    ]
