# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-04 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20171103_0137'),
    ]
    operations = [
        migrations.AddField(
            model_name='foro',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 4, 13, 45, 20, 671000), null=True),
        ),
    ]
