# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-06 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20171104_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 6, 0, 27, 51, 815000), null=True),
        ),
    ]
