# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 03:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20171106_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 26, 22, 32, 34, 652675), null=True),
        ),
    ]
