# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_auto_20171129_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 21, 37, 9, 843080), null=True),
        ),
    ]
