# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_auto_20171130_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 30, 16, 35, 43, 458350), null=True),
        ),
    ]
