# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_auto_20171130_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 2, 16, 26, 11, 380093), null=True),
        ),
    ]
