# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_auto_20171202_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 2, 16, 44, 3, 915263), null=True),
        ),
    ]
