# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_auto_20171202_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 2, 21, 2, 48, 272028), null=True),
        ),
    ]
