# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_auto_20171014_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='cooperativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productor.TipoDocumento'),
        ),
    ]
