# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_auto_20171014_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='email',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
