# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0003_auto_20171015_2043'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                      reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(migrations.RunSQL.noop,
                      reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.AddField(
            model_name='productor',
            name='aprobado',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productor',
            name='cooperativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productor',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productor.TipoDocumento'),
            preserve_default=False,
        ),
    ]
