# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0004_auto_20171015_2053'),
        ('productor', '0004_auto_20171022_1359'),
    ]

    operations = [
    ]
