# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0005_merge_20171022_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCorreos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Envio Correo',
            },
        ),
    ]
