# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import productor.models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0007_productor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('status', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=productor.models.producto.url)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('categorias', models.ManyToManyField(blank=True, to='productor.categoriaProducto')),
            ],
        ),
    ]
