# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0008_categoriaproducto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('productor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productor.Productor')),
                ('productos', models.ManyToManyField(to='productor.producto')),
            ],
        ),
    ]
