# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0009_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
