# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0010_auto_20171129_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(default='lb', max_length=50),
            preserve_default=False,
        ),
    ]
