# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0011_producto_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
