# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0012_auto_20171129_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productor.Productor'),
        ),
    ]
