# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0013_auto_20171129_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='productos',
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productor.producto'),
        ),
    ]
