# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0016_modificar_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
