# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0003_auto_20171008_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
