# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0004_auto_20171101_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=550)),
                ('foto', models.TextField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
