# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0005_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.FloatField(blank=True, null=True)),
                ('semana', models.FloatField(blank=True, null=True)),
                ('dia', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
            options={
                'verbose_name': 'Día de Reparto',
                'verbose_name_plural': 'Días de Reparto',
            },
        ),
    ]
