# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0006_diasreparto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasreparto',
            options={'verbose_name': 'Dia de Reparto', 'verbose_name_plural': 'Dias de Reparto'},
        ),
    ]
