# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171202_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='direccionEntrega',
            field=models.CharField(default='Unkown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedorTarjeta',
            field=models.CharField(default='MasterCard', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='tarjeta',
            field=models.CharField(default='1234-5678-9123-4567', max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='telefonoContacto',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
    ]
